class ResourceRecommender:
    def __init__(self):
        self.resource_data = {
    "Python": "https://www.youtube.com/watch?v=_uQrJ0TkZlc",
    "HTML": "https://www.youtube.com/watch?v=UB1O30fR-EE",
    "CSS": "https://www.youtube.com/watch?v=yfoY53QXEnI",
    "JavaScript": "https://www.youtube.com/watch?v=PkZNo7MFNFg",
    "React": "https://www.youtube.com/watch?v=bMknfKXIFA8",
    "Node.js": "https://www.youtube.com/watch?v=TlB_eWDSMt4",
    "Express.js": "https://www.youtube.com/watch?v=L72fhGm1tfE",
    "MongoDB": "https://www.youtube.com/watch?v=-56x56UppqQ",
    "SQL": "https://www.youtube.com/watch?v=HXV3zeQKqGY",
    "Django": "https://www.youtube.com/watch?v=F5mRW0jo-U4",
    "Flask": "https://www.youtube.com/watch?v=Z1RJmh_OqeA",
    "Java": "https://www.youtube.com/watch?v=UmnCZ7-9yDY",
    "C++": "https://www.youtube.com/watch?v=vLnPwxZdW4Y",
    "C#": "https://www.youtube.com/watch?v=GhQdlIFylQ8",
    "Go": "https://www.youtube.com/watch?v=YS4e4q9oBaU",
    "Rust": "https://www.youtube.com/watch?v=zF34dRivLOw",
    "Kotlin": "https://www.youtube.com/watch?v=F9UC9DY-vIU",
    "Swift": "https://www.youtube.com/watch?v=comQ1-x2a1Q",
    "PHP": "https://www.youtube.com/watch?v=OK_JCtrrv-c",
    "TypeScript": "https://www.youtube.com/watch?v=BwuLxPH8IDs",
    "Bootstrap": "https://www.youtube.com/watch?v=-qfEOE4vtxE",
    "Tailwind CSS": "https://www.youtube.com/watch?v=lCxcTsOHrjo",
    "SASS": "https://www.youtube.com/watch?v=_a5j7KoflTs",
    "jQuery": "https://www.youtube.com/watch?v=htznIeWKgg8",
    "Angular": "https://www.youtube.com/watch?v=2OHbjep_WjQ",
    "Vue.js": "https://www.youtube.com/watch?v=FXpIoQ_rT_c",
    "Next.js": "https://www.youtube.com/watch?v=1WmNXEVia8I",
    "Nuxt.js": "https://www.youtube.com/watch?v=ltzlhAxJr74",
    "Redux": "https://www.youtube.com/watch?v=CVpUuw9XSjY",
    "GraphQL": "https://www.youtube.com/watch?v=ed8SzALpx1Q",
    "REST API": "https://www.youtube.com/watch?v=Q-BpqyOT3a8",
    "Firebase": "https://www.youtube.com/watch?v=9kRgVxULbag",
    "AWS": "https://www.youtube.com/watch?v=ulprqHHWlng",
    "Docker": "https://www.youtube.com/watch?v=3c-iBn73dDE",
    "Kubernetes": "https://www.youtube.com/watch?v=X48VuDVv0do",
    "Git": "https://www.youtube.com/watch?v=8JJ101D3knE",
    "GitHub": "https://www.youtube.com/watch?v=RGOj5yH7evk",
    "CI/CD": "https://www.youtube.com/watch?v=scEDHsr3APg",
    "Linux": "https://www.youtube.com/watch?v=45T3jB5BUzI",
    "Bash": "https://www.youtube.com/watch?v=oxuRxtrO2Ag",
    "Data Structures": "https://www.youtube.com/watch?v=RBSGKlAvoiM",
    "Algorithms": "https://www.youtube.com/watch?v=8hly31xKli0",
    "Machine Learning": "https://www.youtube.com/watch?v=Gv9_4yMHFhI",
    "Deep Learning": "https://www.youtube.com/watch?v=aircAruvnKk",
    "NLP": "https://www.youtube.com/watch?v=8rXD5-xhemo",
    "Computer Vision": "https://www.youtube.com/watch?v=oXlwWbU8l2o",
    "Data Science": "https://www.youtube.com/watch?v=ua-CiDNNj30",
    "Pandas": "https://www.youtube.com/watch?v=vmEHCJofslg",
    "NumPy": "https://www.youtube.com/watch?v=QUT1VHiLmmI",
    "Matplotlib": "https://www.youtube.com/watch?v=DAQNHzOcO5A",
    "Seaborn": "https://www.youtube.com/watch?v=GcXcSZ0gQps",
    "Power BI": "https://www.youtube.com/watch?v=AGrl-H87pRU",
    "Tableau": "https://www.youtube.com/watch?v=9I9DtFOVPIg",
    "Excel": "https://www.youtube.com/watch?v=nqPJJg1n4FY",
}
        
    def get_resource(self, skill):
        return self.resource_data.get(skill)
